var bs_data=[
    {
        "desc":"Naganishia_adeliensis strain 19403212",
        "end":32024,
        "id":"scaffold_1.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":37.9,
                        "code":"PF00610",
                        "end":572,
                        "start":501
                    },
                    {
                        "bitscore":132.0,
                        "code":"PF00621",
                        "end":927,
                        "start":746
                    },
                    {
                        "bitscore":134.7,
                        "code":"PF15405",
                        "end":1103,
                        "start":965
                    },
                    {
                        "bitscore":232.8,
                        "code":"PF00780",
                        "end":1442,
                        "start":1137
                    }
                ],
                "end":7792,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00030_6-_",
                "start":2455,
                "strand":1
            },
            {
                "domains":[],
                "end":8850,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00030_7-_",
                "start":7939,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":258.2,
                        "code":"PF13520",
                        "end":496,
                        "start":53
                    }
                ],
                "end":11357,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00030_8-_",
                "start":9360,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":73.7,
                        "code":"PF07690",
                        "end":377,
                        "start":81
                    }
                ],
                "end":14523,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00030_9-_",
                "start":12493,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.6,
                        "code":"PF00494",
                        "end":340,
                        "start":56
                    }
                ],
                "end":17024,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00031_0-_",
                "start":15000,
                "strand":1
            },
            {
                "domains":[],
                "end":21808,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00031_1-_",
                "start":17288,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":116.9,
                        "code":"PF10261",
                        "end":388,
                        "start":93
                    }
                ],
                "end":23609,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00031_2-_",
                "start":22180,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":33.8,
                        "code":"PF08320",
                        "end":293,
                        "start":129
                    }
                ],
                "end":24783,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00031_3-_",
                "start":23856,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.4,
                        "code":"PF04003",
                        "end":857,
                        "start":752
                    },
                    {
                        "bitscore":39.5,
                        "code":"PF00400",
                        "end":508,
                        "start":470
                    },
                    {
                        "bitscore":13.4,
                        "code":"PF00400",
                        "end":422,
                        "start":384
                    },
                    {
                        "bitscore":23.1,
                        "code":"PF00400",
                        "end":380,
                        "start":341
                    },
                    {
                        "bitscore":16.9,
                        "code":"PF00400",
                        "end":173,
                        "start":135
                    }
                ],
                "end":27892,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00031_4-_",
                "start":24904,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.2,
                        "code":"PF06677",
                        "end":57,
                        "start":10
                    },
                    {
                        "bitscore":28.4,
                        "code":"PF06677",
                        "end":214,
                        "start":159
                    }
                ],
                "end":29525,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00031_5-_",
                "start":28210,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_albida strain 20661800",
        "end":32802,
        "id":"scaffold_10.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":855.9,
                        "code":"PF00012",
                        "end":611,
                        "start":4
                    }
                ],
                "end":3873,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003103-_T1",
                "start":1463,
                "strand":1
            },
            {
                "domains":[],
                "end":6550,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003104-_T1",
                "start":4505,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.3,
                        "code":"PF13857",
                        "end":102,
                        "start":45
                    }
                ],
                "end":7665,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003105-_T1",
                "start":6673,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.2,
                        "code":"PF16450",
                        "end":194,
                        "start":121
                    },
                    {
                        "bitscore":137.4,
                        "code":"PF00004",
                        "end":385,
                        "start":252
                    },
                    {
                        "bitscore":42.0,
                        "code":"PF17862",
                        "end":451,
                        "start":407
                    }
                ],
                "end":9798,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003106-_T1",
                "start":7899,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":146.7,
                        "code":"PF11911",
                        "end":281,
                        "start":122
                    }
                ],
                "end":11896,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003107-_T1",
                "start":10006,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.7,
                        "code":"PF13249",
                        "end":119,
                        "start":6
                    },
                    {
                        "bitscore":151.2,
                        "code":"PF13243",
                        "end":628,
                        "start":294
                    }
                ],
                "end":17802,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003108-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":51.3,
                        "code":"PF03460",
                        "end":1293,
                        "start":1224
                    },
                    {
                        "bitscore":171.8,
                        "code":"PF01077",
                        "end":1206,
                        "start":1044
                    },
                    {
                        "bitscore":59.0,
                        "code":"PF03460",
                        "end":1011,
                        "start":944
                    },
                    {
                        "bitscore":99.0,
                        "code":"PF00258",
                        "end":865,
                        "start":722
                    }
                ],
                "end":22673,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003109-_T1",
                "start":18261,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":134.5,
                        "code":"PF00202",
                        "end":498,
                        "start":324
                    },
                    {
                        "bitscore":158.5,
                        "code":"PF00202",
                        "end":313,
                        "start":71
                    }
                ],
                "end":24815,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003110-_T1",
                "start":23116,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":966.3,
                        "code":"PF12449",
                        "end":1357,
                        "start":204
                    }
                ],
                "end":31719,
                "id":"ncbi_NaganishiaalbidaGCA023628155.1_003111-_T1",
                "start":26362,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_antarctica strain 21218161",
        "end":32388,
        "id":"scaffold_100.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":27.1,
                        "code":"PF03810",
                        "end":102,
                        "start":35
                    },
                    {
                        "bitscore":76.2,
                        "code":"PF08389",
                        "end":257,
                        "start":112
                    }
                ],
                "end":4236,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00545_9-_",
                "start":854,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":85.9,
                        "code":"PF03399",
                        "end":484,
                        "start":250
                    }
                ],
                "end":7064,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00546_0-_",
                "start":4787,
                "strand":-1
            },
            {
                "domains":[],
                "end":9863,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00546_1-_",
                "start":7771,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":182.6,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    },
                    {
                        "bitscore":132.8,
                        "code":"PF11861",
                        "end":423,
                        "start":262
                    },
                    {
                        "bitscore":264.0,
                        "code":"PF07780",
                        "end":917,
                        "start":699
                    }
                ],
                "end":14687,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00546_2-_",
                "start":11610,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":145.9,
                        "code":"PF00494",
                        "end":631,
                        "start":337
                    }
                ],
                "end":17388,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00546_3-_",
                "start":15000,
                "strand":1
            },
            {
                "domains":[],
                "end":22204,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00546_4-_",
                "start":19485,
                "strand":1
            },
            {
                "domains":[],
                "end":25624,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00546_5-_",
                "start":23630,
                "strand":1
            },
            {
                "domains":[],
                "end":28001,
                "id":"ncbi_NaganishiaantarcticaGCA025758675.1_00546_6-_",
                "start":26876,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_cerealis strain Annotation submitted by Jet Propulsion Laboratory, California Institute of Technology",
        "end":32389,
        "id":"scaffold_105.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":29.4,
                        "code":"PF05721",
                        "end":256,
                        "start":33
                    }
                ],
                "end":2112,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007718-_T1",
                "start":881,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.9,
                        "code":"PF07690",
                        "end":496,
                        "start":80
                    }
                ],
                "end":5087,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007719-_T1",
                "start":2848,
                "strand":1
            },
            {
                "domains":[],
                "end":7831,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007720-_T1",
                "start":5538,
                "strand":-1
            },
            {
                "domains":[],
                "end":10010,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007721-_T1",
                "start":9059,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.4,
                        "code":"PF03810",
                        "end":102,
                        "start":35
                    },
                    {
                        "bitscore":76.6,
                        "code":"PF08389",
                        "end":257,
                        "start":112
                    }
                ],
                "end":14288,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007722-_T1",
                "start":10862,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":114.8,
                        "code":"PF00494",
                        "end":631,
                        "start":355
                    }
                ],
                "end":17389,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007723-_T1",
                "start":15000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":264.6,
                        "code":"PF07780",
                        "end":926,
                        "start":689
                    },
                    {
                        "bitscore":133.4,
                        "code":"PF11861",
                        "end":422,
                        "start":261
                    },
                    {
                        "bitscore":185.2,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    }
                ],
                "end":20721,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007724-_T1",
                "start":17605,
                "strand":-1
            },
            {
                "domains":[],
                "end":24823,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007725-_T1",
                "start":23692,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.5,
                        "code":"PF03399",
                        "end":449,
                        "start":215
                    }
                ],
                "end":27591,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007726-_T1",
                "start":25227,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.2,
                        "code":"PF00005",
                        "end":108,
                        "start":2
                    },
                    {
                        "bitscore":26.4,
                        "code":"PF19055",
                        "end":258,
                        "start":137
                    },
                    {
                        "bitscore":139.5,
                        "code":"PF01061",
                        "end":472,
                        "start":255
                    }
                ],
                "end":30440,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_007727-_T1",
                "start":28703,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_onofrii strain Annotation submitted by Jet Propulsion Laboratory, California Institute of Technology",
        "end":32231,
        "id":"scaffold_11.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":36.7,
                        "code":"PF13857",
                        "end":79,
                        "start":14
                    }
                ],
                "end":2158,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003488-_T1",
                "start":1161,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.8,
                        "code":"PF08647",
                        "end":674,
                        "start":580
                    }
                ],
                "end":5789,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003489-_T1",
                "start":2531,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.9,
                        "code":"PF00498",
                        "end":124,
                        "start":57
                    }
                ],
                "end":11719,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003490-_T1",
                "start":6662,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":259.0,
                        "code":"PF00248",
                        "end":317,
                        "start":20
                    }
                ],
                "end":13389,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003491-_T1",
                "start":11922,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":131.7,
                        "code":"PF03073",
                        "end":176,
                        "start":18
                    }
                ],
                "end":14798,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003492-_T1",
                "start":14012,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":126.2,
                        "code":"PF00494",
                        "end":340,
                        "start":56
                    }
                ],
                "end":17231,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003493-_T1",
                "start":15000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":55.6,
                        "code":"PF07690",
                        "end":388,
                        "start":86
                    }
                ],
                "end":20191,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003494-_T1",
                "start":18012,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":261.1,
                        "code":"PF13520",
                        "end":492,
                        "start":50
                    }
                ],
                "end":22999,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003495-_T1",
                "start":20989,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.0,
                        "code":"PF04082",
                        "end":149,
                        "start":10
                    }
                ],
                "end":25136,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003496-_T1",
                "start":23770,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":22.9,
                        "code":"PF00172",
                        "end":113,
                        "start":51
                    }
                ],
                "end":27715,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003497-_T1",
                "start":25523,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":111.4,
                        "code":"PF07200",
                        "end":207,
                        "start":13
                    }
                ],
                "end":28913,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003498-_T1",
                "start":27937,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":55.9,
                        "code":"PF03167",
                        "end":397,
                        "start":228
                    }
                ],
                "end":31413,
                "id":"ncbi_NaganishiaonofriiGCA030039215.1_003499-_T1",
                "start":29195,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_sp._KV-2022a strain 27861060",
        "end":28644,
        "id":"scaffold_116.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":9384,
                "id":"ncbi_Naganishiasp.KV-_2022aGCA022813745.1_006967_",
                "start":7926,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":156.8,
                        "code":"PF00494",
                        "end":627,
                        "start":330
                    }
                ],
                "end":13644,
                "id":"ncbi_Naganishiasp.KV-_2022aGCA022813745.1_006968_",
                "start":11332,
                "strand":-1
            },
            {
                "domains":[],
                "end":16276,
                "id":"ncbi_Naganishiasp.KV-_2022aGCA022813745.1_006969_",
                "start":14261,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":182.5,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    },
                    {
                        "bitscore":137.7,
                        "code":"PF11861",
                        "end":425,
                        "start":264
                    },
                    {
                        "bitscore":268.2,
                        "code":"PF07780",
                        "end":918,
                        "start":700
                    }
                ],
                "end":19744,
                "id":"ncbi_Naganishiasp.KV-_2022aGCA022813745.1_006970_",
                "start":16719,
                "strand":1
            },
            {
                "domains":[],
                "end":22376,
                "id":"ncbi_Naganishiasp.KV-_2022aGCA022813745.1_006971_",
                "start":20360,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.4,
                        "code":"PF03399",
                        "end":480,
                        "start":249
                    }
                ],
                "end":25180,
                "id":"ncbi_Naganishiasp.KV-_2022aGCA022813745.1_006972_",
                "start":22933,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_albida strain 19422953",
        "end":32223,
        "id":"scaffold_12.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":109.2,
                        "code":"PF10791",
                        "end":93,
                        "start":5
                    }
                ],
                "end":4072,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003041-_T1",
                "start":3141,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.3,
                        "code":"PF08620",
                        "end":315,
                        "start":247
                    },
                    {
                        "bitscore":37.8,
                        "code":"PF08621",
                        "end":149,
                        "start":104
                    }
                ],
                "end":7925,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003042-_T1",
                "start":4335,
                "strand":-1
            },
            {
                "domains":[],
                "end":10019,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003043-_T1",
                "start":8423,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":185.7,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    },
                    {
                        "bitscore":133.8,
                        "code":"PF11861",
                        "end":423,
                        "start":262
                    },
                    {
                        "bitscore":266.7,
                        "code":"PF07780",
                        "end":924,
                        "start":707
                    }
                ],
                "end":14709,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003044-_T1",
                "start":11659,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.9,
                        "code":"PF00494",
                        "end":598,
                        "start":320
                    }
                ],
                "end":17223,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003045-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[],
                "end":23356,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003046-_T1",
                "start":20943,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":198.6,
                        "code":"PF07933",
                        "end":167,
                        "start":11
                    }
                ],
                "end":24561,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003047-_T1",
                "start":23659,
                "strand":1
            },
            {
                "domains":[],
                "end":31976,
                "id":"ncbi_NaganishiaalbidaGCA012922605.1_003048-_T1",
                "start":25334,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_friedmannii strain Annotation submitted by Jet Propulsion Laboratory, California Institute of Technology",
        "end":56177,
        "id":"scaffold_13.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":316.7,
                        "code":"PF00202",
                        "end":478,
                        "start":76
                    }
                ],
                "end":1718,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_75_",
                "start":1,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":98.1,
                        "code":"PF00258",
                        "end":921,
                        "start":778
                    },
                    {
                        "bitscore":60.8,
                        "code":"PF03460",
                        "end":1067,
                        "start":1001
                    },
                    {
                        "bitscore":167.8,
                        "code":"PF01077",
                        "end":1262,
                        "start":1100
                    },
                    {
                        "bitscore":52.3,
                        "code":"PF03460",
                        "end":1349,
                        "start":1280
                    }
                ],
                "end":7081,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_76_",
                "start":2360,
                "strand":1
            },
            {
                "domains":[],
                "end":9669,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_77_",
                "start":8245,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":169.1,
                        "code":"PF13243",
                        "end":718,
                        "start":384
                    },
                    {
                        "bitscore":155.2,
                        "code":"PF13249",
                        "end":375,
                        "start":79
                    }
                ],
                "end":14289,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_78_",
                "start":10228,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":156.1,
                        "code":"PF04912",
                        "end":509,
                        "start":18
                    }
                ],
                "end":16679,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_79_",
                "start":14642,
                "strand":1
            },
            {
                "domains":[],
                "end":22187,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_80_",
                "start":19979,
                "strand":-1
            },
            {
                "domains":[],
                "end":26518,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_81_",
                "start":25204,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":239.8,
                        "code":"PF00091",
                        "end":212,
                        "start":3
                    },
                    {
                        "bitscore":132.0,
                        "code":"PF03953",
                        "end":383,
                        "start":261
                    }
                ],
                "end":28605,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_82_",
                "start":27075,
                "strand":1
            },
            {
                "domains":[],
                "end":31240,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_83_",
                "start":29740,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":30.9,
                        "code":"PF00172",
                        "end":244,
                        "start":204
                    }
                ],
                "end":36007,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_84_",
                "start":32740,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.2,
                        "code":"PF13249",
                        "end":185,
                        "start":79
                    },
                    {
                        "bitscore":168.6,
                        "code":"PF13243",
                        "end":665,
                        "start":331
                    }
                ],
                "end":41177,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_85_",
                "start":37057,
                "strand":1
            },
            {
                "domains":[],
                "end":44102,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_86_",
                "start":42063,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":128.8,
                        "code":"PF10350",
                        "end":234,
                        "start":1
                    }
                ],
                "end":46928,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_87_",
                "start":44219,
                "strand":1
            },
            {
                "domains":[],
                "end":49014,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_88_",
                "start":47208,
                "strand":-1
            },
            {
                "domains":[],
                "end":49777,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_89_",
                "start":49403,
                "strand":-1
            },
            {
                "domains":[],
                "end":51880,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_90_",
                "start":50178,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":122.8,
                        "code":"PF07690",
                        "end":506,
                        "start":152
                    }
                ],
                "end":55777,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0038_91_",
                "start":52796,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_randhawae strain 20271596",
        "end":25243,
        "id":"scaffold_140.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":1486,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_005993_-T1",
                "start":497,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":261.4,
                        "code":"PF13520",
                        "end":495,
                        "start":53
                    }
                ],
                "end":4073,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_005994_-T1",
                "start":2043,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.5,
                        "code":"PF00494",
                        "end":340,
                        "start":56
                    }
                ],
                "end":10243,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_005995_-T1",
                "start":8038,
                "strand":1
            },
            {
                "domains":[],
                "end":14948,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_005996_-T1",
                "start":10474,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":123.6,
                        "code":"PF10261",
                        "end":378,
                        "start":83
                    }
                ],
                "end":16644,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_005997_-T1",
                "start":15247,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.0,
                        "code":"PF08320",
                        "end":98,
                        "start":17
                    },
                    {
                        "bitscore":28.1,
                        "code":"PF08320",
                        "end":332,
                        "start":161
                    }
                ],
                "end":17953,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_005998_-T1",
                "start":16918,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":83.3,
                        "code":"PF04003",
                        "end":857,
                        "start":752
                    },
                    {
                        "bitscore":36.3,
                        "code":"PF00400",
                        "end":508,
                        "start":470
                    },
                    {
                        "bitscore":13.4,
                        "code":"PF00400",
                        "end":422,
                        "start":384
                    },
                    {
                        "bitscore":23.1,
                        "code":"PF00400",
                        "end":380,
                        "start":341
                    },
                    {
                        "bitscore":20.8,
                        "code":"PF00400",
                        "end":173,
                        "start":136
                    }
                ],
                "end":21144,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_005999_-T1",
                "start":18128,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":40.5,
                        "code":"PF06677",
                        "end":57,
                        "start":10
                    },
                    {
                        "bitscore":30.2,
                        "code":"PF06677",
                        "end":206,
                        "start":152
                    }
                ],
                "end":23057,
                "id":"ncbi_NaganishiarandhawaeGCA013461525.1_006000_-T1",
                "start":21753,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_liquefaciens strain 19471643",
        "end":32223,
        "id":"scaffold_15.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":6889,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_32_",
                "start":247,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":198.6,
                        "code":"PF07933",
                        "end":167,
                        "start":11
                    }
                ],
                "end":8564,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_32_",
                "start":7662,
                "strand":-1
            },
            {
                "domains":[],
                "end":11280,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_32_",
                "start":8867,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":149.0,
                        "code":"PF00494",
                        "end":584,
                        "start":306
                    }
                ],
                "end":17223,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_32_",
                "start":15000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":266.7,
                        "code":"PF07780",
                        "end":940,
                        "start":723
                    },
                    {
                        "bitscore":132.8,
                        "code":"PF11861",
                        "end":439,
                        "start":262
                    },
                    {
                        "bitscore":185.7,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    }
                ],
                "end":20564,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_32_",
                "start":17514,
                "strand":-1
            },
            {
                "domains":[],
                "end":23800,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_33_",
                "start":22204,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.8,
                        "code":"PF08621",
                        "end":149,
                        "start":104
                    },
                    {
                        "bitscore":75.3,
                        "code":"PF08620",
                        "end":315,
                        "start":247
                    }
                ],
                "end":27888,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_33_",
                "start":24298,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.2,
                        "code":"PF10791",
                        "end":93,
                        "start":5
                    }
                ],
                "end":29082,
                "id":"ncbi_NaganishialiquefaciensGCA019775365.1_003_33_",
                "start":28151,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_adeliensis strain 19403212",
        "end":32223,
        "id":"scaffold_16.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":109.2,
                        "code":"PF10791",
                        "end":93,
                        "start":5
                    }
                ],
                "end":4072,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_0-_",
                "start":3141,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.3,
                        "code":"PF08620",
                        "end":315,
                        "start":247
                    },
                    {
                        "bitscore":37.8,
                        "code":"PF08621",
                        "end":149,
                        "start":104
                    }
                ],
                "end":7925,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_1-_",
                "start":4335,
                "strand":-1
            },
            {
                "domains":[],
                "end":10019,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_2-_",
                "start":8423,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":185.7,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    },
                    {
                        "bitscore":133.8,
                        "code":"PF11861",
                        "end":423,
                        "start":262
                    },
                    {
                        "bitscore":266.7,
                        "code":"PF07780",
                        "end":924,
                        "start":707
                    }
                ],
                "end":14709,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_3-_",
                "start":11659,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.9,
                        "code":"PF00494",
                        "end":598,
                        "start":320
                    }
                ],
                "end":17223,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_4-_",
                "start":15000,
                "strand":1
            },
            {
                "domains":[],
                "end":23356,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_5-_",
                "start":20943,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":198.6,
                        "code":"PF07933",
                        "end":167,
                        "start":11
                    }
                ],
                "end":24561,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_6-_",
                "start":23659,
                "strand":1
            },
            {
                "domains":[],
                "end":28019,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_7-_",
                "start":25334,
                "strand":1
            },
            {
                "domains":[],
                "end":31976,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00388_8-_",
                "start":30625,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_liquefaciens strain Annotation submitted by School of Life Science and Technology, Tokyo Institute of Technology",
        "end":32226,
        "id":"scaffold_17.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":6890,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_13_",
                "start":246,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":198.6,
                        "code":"PF07933",
                        "end":167,
                        "start":11
                    }
                ],
                "end":8566,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_13_",
                "start":7663,
                "strand":-1
            },
            {
                "domains":[],
                "end":11282,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_13_",
                "start":8869,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":147.5,
                        "code":"PF00494",
                        "end":557,
                        "start":279
                    }
                ],
                "end":17226,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_14_",
                "start":15000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":266.7,
                        "code":"PF07780",
                        "end":940,
                        "start":723
                    },
                    {
                        "bitscore":132.8,
                        "code":"PF11861",
                        "end":439,
                        "start":262
                    },
                    {
                        "bitscore":185.7,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    }
                ],
                "end":20572,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_14_",
                "start":17522,
                "strand":-1
            },
            {
                "domains":[],
                "end":23793,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_14_",
                "start":22228,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.8,
                        "code":"PF08621",
                        "end":149,
                        "start":104
                    },
                    {
                        "bitscore":75.3,
                        "code":"PF08620",
                        "end":315,
                        "start":247
                    }
                ],
                "end":27881,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_14_",
                "start":24291,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.2,
                        "code":"PF10791",
                        "end":93,
                        "start":5
                    }
                ],
                "end":29075,
                "id":"ncbi_NaganishialiquefaciensGCA013423385.1_005_14_",
                "start":28144,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_albida strain 20845140",
        "end":33193,
        "id":"scaffold_19.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":962.9,
                        "code":"PF12449",
                        "end":1357,
                        "start":204
                    }
                ],
                "end":7381,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004834-_T1",
                "start":1083,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":308.6,
                        "code":"PF00202",
                        "end":478,
                        "start":71
                    }
                ],
                "end":9686,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004835-_T1",
                "start":7987,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":99.0,
                        "code":"PF00258",
                        "end":865,
                        "start":722
                    },
                    {
                        "bitscore":59.0,
                        "code":"PF03460",
                        "end":1011,
                        "start":944
                    },
                    {
                        "bitscore":171.8,
                        "code":"PF01077",
                        "end":1206,
                        "start":1044
                    },
                    {
                        "bitscore":51.3,
                        "code":"PF03460",
                        "end":1293,
                        "start":1224
                    }
                ],
                "end":14541,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004836-_T1",
                "start":10129,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":151.4,
                        "code":"PF13243",
                        "end":715,
                        "start":381
                    },
                    {
                        "bitscore":86.0,
                        "code":"PF13249",
                        "end":207,
                        "start":64
                    }
                ],
                "end":18193,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004837-_T1",
                "start":15000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":146.7,
                        "code":"PF11911",
                        "end":281,
                        "start":122
                    }
                ],
                "end":22796,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004838-_T1",
                "start":20906,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.1,
                        "code":"PF17862",
                        "end":447,
                        "start":403
                    },
                    {
                        "bitscore":137.4,
                        "code":"PF00004",
                        "end":381,
                        "start":248
                    },
                    {
                        "bitscore":60.2,
                        "code":"PF16450",
                        "end":190,
                        "start":117
                    }
                ],
                "end":24903,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004839-_T1",
                "start":23004,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.1,
                        "code":"PF13637",
                        "end":75,
                        "start":24
                    }
                ],
                "end":26129,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004840-_T1",
                "start":25137,
                "strand":1
            },
            {
                "domains":[],
                "end":28297,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004841-_T1",
                "start":26252,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":855.9,
                        "code":"PF00012",
                        "end":611,
                        "start":4
                    }
                ],
                "end":31339,
                "id":"ncbi_NaganishiaalbidaGCA023628175.1_004842-_T1",
                "start":28929,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_cerealis strain Annotation submitted by Jet Propulsion Laboratory, California Institute of Technology",
        "end":31353,
        "id":"scaffold_30.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":67.5,
                        "code":"PF07173",
                        "end":433,
                        "start":314
                    }
                ],
                "end":2180,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003155-_T1",
                "start":224,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.6,
                        "code":"PF00172",
                        "end":65,
                        "start":24
                    },
                    {
                        "bitscore":55.4,
                        "code":"PF04082",
                        "end":457,
                        "start":183
                    }
                ],
                "end":5083,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003156-_T1",
                "start":3013,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":121.5,
                        "code":"PF00701",
                        "end":302,
                        "start":4
                    }
                ],
                "end":6155,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003157-_T1",
                "start":5228,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":289.2,
                        "code":"PF00083",
                        "end":451,
                        "start":3
                    }
                ],
                "end":8381,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003158-_T1",
                "start":6854,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.4,
                        "code":"PF08590",
                        "end":90,
                        "start":27
                    },
                    {
                        "bitscore":41.9,
                        "code":"PF01713",
                        "end":174,
                        "start":98
                    }
                ],
                "end":9327,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003159-_T1",
                "start":8592,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":173.9,
                        "code":"PF00071",
                        "end":182,
                        "start":10
                    }
                ],
                "end":10168,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003160-_T1",
                "start":9520,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":85.9,
                        "code":"PF00248",
                        "end":276,
                        "start":26
                    }
                ],
                "end":11376,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003161-_T1",
                "start":10425,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.6,
                        "code":"PF03358",
                        "end":147,
                        "start":14
                    }
                ],
                "end":12122,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003162-_T1",
                "start":11519,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":295.3,
                        "code":"PF03985",
                        "end":415,
                        "start":8
                    }
                ],
                "end":13647,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003163-_T1",
                "start":12399,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.4,
                        "code":"PF04424",
                        "end":187,
                        "start":37
                    }
                ],
                "end":14904,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003164-_T1",
                "start":13827,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":153.7,
                        "code":"PF00494",
                        "end":331,
                        "start":46
                    }
                ],
                "end":16353,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003165-_T1",
                "start":15000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":313.7,
                        "code":"PF04670",
                        "end":249,
                        "start":8
                    }
                ],
                "end":17533,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003166-_T1",
                "start":16549,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.0,
                        "code":"PF00076",
                        "end":114,
                        "start":44
                    }
                ],
                "end":18376,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003167-_T1",
                "start":17779,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":87.7,
                        "code":"PF00069",
                        "end":314,
                        "start":27
                    }
                ],
                "end":21140,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003168-_T1",
                "start":18641,
                "strand":1
            },
            {
                "domains":[],
                "end":22772,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003169-_T1",
                "start":21833,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.9,
                        "code":"PF13537",
                        "end":256,
                        "start":151
                    },
                    {
                        "bitscore":50.4,
                        "code":"PF00733",
                        "end":645,
                        "start":471
                    }
                ],
                "end":24928,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003170-_T1",
                "start":22969,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.5,
                        "code":"PF03061",
                        "end":173,
                        "start":98
                    }
                ],
                "end":25608,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003171-_T1",
                "start":24999,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":52.8,
                        "code":"PF00107",
                        "end":302,
                        "start":222
                    }
                ],
                "end":27059,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003172-_T1",
                "start":25829,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":88.3,
                        "code":"PF00561",
                        "end":262,
                        "start":24
                    }
                ],
                "end":28161,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003173-_T1",
                "start":27333,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":87.4,
                        "code":"PF01370",
                        "end":263,
                        "start":15
                    }
                ],
                "end":29301,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003174-_T1",
                "start":28224,
                "strand":-1
            },
            {
                "domains":[],
                "end":30528,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_003175-_T1",
                "start":29700,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_albida strain 20697359",
        "end":21183,
        "id":"scaffold_37.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":88.6,
                        "code":"PF03399",
                        "end":477,
                        "start":251
                    }
                ],
                "end":4078,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_006460-_T1",
                "start":1830,
                "strand":-1
            },
            {
                "domains":[],
                "end":6565,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_006461-_T1",
                "start":4543,
                "strand":-1
            },
            {
                "domains":[],
                "end":11120,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_006462-_T1",
                "start":9135,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":184.0,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    },
                    {
                        "bitscore":139.3,
                        "code":"PF11861",
                        "end":425,
                        "start":264
                    },
                    {
                        "bitscore":268.9,
                        "code":"PF07780",
                        "end":920,
                        "start":702
                    }
                ],
                "end":14640,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_006463-_T1",
                "start":11602,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":147.3,
                        "code":"PF00494",
                        "end":628,
                        "start":331
                    }
                ],
                "end":17324,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_006464-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[],
                "end":21115,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_006465-_T1",
                "start":20268,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_albida strain 20697359",
        "end":32017,
        "id":"scaffold_4.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2037,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001673-_T1",
                "start":674,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":448.4,
                        "code":"PF09794",
                        "end":513,
                        "start":123
                    }
                ],
                "end":10503,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001674-_T1",
                "start":7291,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":164.0,
                        "code":"PF01266",
                        "end":435,
                        "start":32
                    }
                ],
                "end":12541,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001675-_T1",
                "start":10762,
                "strand":1
            },
            {
                "domains":[],
                "end":14174,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001676-_T1",
                "start":13116,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":123.3,
                        "code":"PF00494",
                        "end":325,
                        "start":41
                    }
                ],
                "end":17017,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001677-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.4,
                        "code":"PF14310",
                        "end":781,
                        "start":711
                    },
                    {
                        "bitscore":175.1,
                        "code":"PF01915",
                        "end":653,
                        "start":403
                    },
                    {
                        "bitscore":103.5,
                        "code":"PF00933",
                        "end":355,
                        "start":85
                    }
                ],
                "end":20305,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001678-_T1",
                "start":17299,
                "strand":-1
            },
            {
                "domains":[],
                "end":24885,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001679-_T1",
                "start":21805,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.1,
                        "code":"PF00240",
                        "end":75,
                        "start":4
                    },
                    {
                        "bitscore":51.6,
                        "code":"PF00627",
                        "end":195,
                        "start":159
                    },
                    {
                        "bitscore":76.1,
                        "code":"PF09280",
                        "end":344,
                        "start":288
                    },
                    {
                        "bitscore":34.2,
                        "code":"PF00627",
                        "end":411,
                        "start":375
                    }
                ],
                "end":27093,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001680-_T1",
                "start":25265,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":56.4,
                        "code":"PF06966",
                        "end":252,
                        "start":109
                    }
                ],
                "end":31747,
                "id":"ncbi_NaganishiaalbidaGCA001599735.1_001681-_T1",
                "start":30794,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_albida strain 20877543",
        "end":32017,
        "id":"scaffold_54.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2034,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005632-_T1",
                "start":787,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":150.6,
                        "code":"PF04042",
                        "end":497,
                        "start":292
                    }
                ],
                "end":7115,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005633-_T1",
                "start":4706,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":449.8,
                        "code":"PF09794",
                        "end":513,
                        "start":123
                    }
                ],
                "end":10494,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005634-_T1",
                "start":7285,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":163.7,
                        "code":"PF01266",
                        "end":463,
                        "start":32
                    }
                ],
                "end":12536,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005635-_T1",
                "start":10759,
                "strand":1
            },
            {
                "domains":[],
                "end":14174,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005636-_T1",
                "start":13110,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":122.3,
                        "code":"PF00494",
                        "end":340,
                        "start":56
                    }
                ],
                "end":17017,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005637-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.4,
                        "code":"PF14310",
                        "end":781,
                        "start":711
                    },
                    {
                        "bitscore":176.2,
                        "code":"PF01915",
                        "end":653,
                        "start":403
                    },
                    {
                        "bitscore":102.7,
                        "code":"PF00933",
                        "end":355,
                        "start":81
                    }
                ],
                "end":20305,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005638-_T1",
                "start":17299,
                "strand":-1
            },
            {
                "domains":[],
                "end":24890,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005639-_T1",
                "start":21810,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.1,
                        "code":"PF00240",
                        "end":75,
                        "start":4
                    },
                    {
                        "bitscore":51.7,
                        "code":"PF00627",
                        "end":195,
                        "start":159
                    },
                    {
                        "bitscore":76.1,
                        "code":"PF09280",
                        "end":343,
                        "start":287
                    },
                    {
                        "bitscore":34.2,
                        "code":"PF00627",
                        "end":410,
                        "start":374
                    }
                ],
                "end":27101,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005640-_T1",
                "start":25270,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":56.4,
                        "code":"PF06966",
                        "end":252,
                        "start":109
                    }
                ],
                "end":31764,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_005641-_T1",
                "start":30811,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_cerealis strain Annotation submitted by Jet Propulsion Laboratory, California Institute of Technology",
        "end":31082,
        "id":"scaffold_60.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":204.2,
                        "code":"PF01425",
                        "end":504,
                        "start":92
                    }
                ],
                "end":4844,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005310-_T1",
                "start":2349,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":155.8,
                        "code":"PF04912",
                        "end":504,
                        "start":122
                    }
                ],
                "end":7552,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005311-_T1",
                "start":5712,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":148.9,
                        "code":"PF13249",
                        "end":332,
                        "start":66
                    },
                    {
                        "bitscore":91.7,
                        "code":"PF13243",
                        "end":573,
                        "start":341
                    }
                ],
                "end":10613,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005312-_T1",
                "start":8102,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":111.2,
                        "code":"PF13243",
                        "end":221,
                        "start":1
                    }
                ],
                "end":16082,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005313-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.6,
                        "code":"PF09335",
                        "end":350,
                        "start":229
                    }
                ],
                "end":19827,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005314-_T1",
                "start":17310,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.3,
                        "code":"PF03009",
                        "end":256,
                        "start":178
                    },
                    {
                        "bitscore":77.7,
                        "code":"PF03009",
                        "end":155,
                        "start":34
                    }
                ],
                "end":22156,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005315-_T1",
                "start":20446,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":38.2,
                        "code":"PF14604",
                        "end":437,
                        "start":388
                    }
                ],
                "end":25086,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005316-_T1",
                "start":23208,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":99.3,
                        "code":"PF12756",
                        "end":309,
                        "start":197
                    },
                    {
                        "bitscore":33.0,
                        "code":"PF12171",
                        "end":98,
                        "start":75
                    }
                ],
                "end":29303,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_005317-_T1",
                "start":27505,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_albida strain 20877543",
        "end":33195,
        "id":"scaffold_8.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":855.9,
                        "code":"PF00012",
                        "end":611,
                        "start":4
                    }
                ],
                "end":4311,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001801-_T1",
                "start":1899,
                "strand":1
            },
            {
                "domains":[],
                "end":6991,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001802-_T1",
                "start":4945,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.3,
                        "code":"PF13857",
                        "end":102,
                        "start":45
                    }
                ],
                "end":8109,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001803-_T1",
                "start":7114,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.2,
                        "code":"PF16450",
                        "end":193,
                        "start":120
                    },
                    {
                        "bitscore":137.4,
                        "code":"PF00004",
                        "end":384,
                        "start":251
                    },
                    {
                        "bitscore":42.0,
                        "code":"PF17862",
                        "end":450,
                        "start":406
                    }
                ],
                "end":10240,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001804-_T1",
                "start":8343,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":146.7,
                        "code":"PF11911",
                        "end":281,
                        "start":122
                    }
                ],
                "end":12338,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001805-_T1",
                "start":10448,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.1,
                        "code":"PF13249",
                        "end":244,
                        "start":108
                    },
                    {
                        "bitscore":149.0,
                        "code":"PF13243",
                        "end":738,
                        "start":404
                    }
                ],
                "end":18195,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001806-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":51.3,
                        "code":"PF03460",
                        "end":1293,
                        "start":1224
                    },
                    {
                        "bitscore":170.8,
                        "code":"PF01077",
                        "end":1206,
                        "start":1044
                    },
                    {
                        "bitscore":59.0,
                        "code":"PF03460",
                        "end":1011,
                        "start":944
                    },
                    {
                        "bitscore":99.0,
                        "code":"PF00258",
                        "end":865,
                        "start":722
                    }
                ],
                "end":23066,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001807-_T1",
                "start":18654,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":308.4,
                        "code":"PF00202",
                        "end":478,
                        "start":71
                    }
                ],
                "end":25238,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001808-_T1",
                "start":23540,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":966.8,
                        "code":"PF12449",
                        "end":1357,
                        "start":204
                    }
                ],
                "end":32140,
                "id":"ncbi_NaganishiaalbidaGCA001468955.1_001809-_T1",
                "start":26783,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_cerealis strain Annotation submitted by Jet Propulsion Laboratory, California Institute of Technology",
        "end":32113,
        "id":"scaffold_84.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":40.8,
                        "code":"PF00610",
                        "end":652,
                        "start":581
                    },
                    {
                        "bitscore":126.9,
                        "code":"PF00621",
                        "end":1008,
                        "start":827
                    },
                    {
                        "bitscore":131.2,
                        "code":"PF15405",
                        "end":1184,
                        "start":1046
                    },
                    {
                        "bitscore":135.5,
                        "code":"PF00780",
                        "end":1439,
                        "start":1218
                    }
                ],
                "end":7156,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006676-_T1",
                "start":1298,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":260.8,
                        "code":"PF13520",
                        "end":495,
                        "start":52
                    }
                ],
                "end":10923,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006677-_T1",
                "start":8893,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.0,
                        "code":"PF07690",
                        "end":402,
                        "start":202
                    }
                ],
                "end":14383,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006678-_T1",
                "start":12172,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.5,
                        "code":"PF00494",
                        "end":340,
                        "start":56
                    }
                ],
                "end":17113,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006679-_T1",
                "start":15000,
                "strand":1
            },
            {
                "domains":[],
                "end":21807,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006680-_T1",
                "start":17336,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.3,
                        "code":"PF10261",
                        "end":378,
                        "start":83
                    }
                ],
                "end":23436,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006681-_T1",
                "start":22033,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":26.1,
                        "code":"PF08320",
                        "end":129,
                        "start":16
                    },
                    {
                        "bitscore":31.8,
                        "code":"PF08320",
                        "end":331,
                        "start":155
                    }
                ],
                "end":24704,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006682-_T1",
                "start":23672,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":82.7,
                        "code":"PF04003",
                        "end":857,
                        "start":752
                    },
                    {
                        "bitscore":36.5,
                        "code":"PF00400",
                        "end":508,
                        "start":470
                    },
                    {
                        "bitscore":13.4,
                        "code":"PF00400",
                        "end":422,
                        "start":384
                    },
                    {
                        "bitscore":23.1,
                        "code":"PF00400",
                        "end":380,
                        "start":341
                    },
                    {
                        "bitscore":20.8,
                        "code":"PF00400",
                        "end":173,
                        "start":136
                    }
                ],
                "end":27903,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006683-_T1",
                "start":24887,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.7,
                        "code":"PF06677",
                        "end":57,
                        "start":10
                    }
                ],
                "end":29819,
                "id":"ncbi_NaganishiacerealisGCA030039265.1_006684-_T1",
                "start":28511,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_friedmannii strain Annotation submitted by Jet Propulsion Laboratory, California Institute of Technology",
        "end":32483,
        "id":"scaffold_9.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":28.9,
                        "code":"PF13537",
                        "end":190,
                        "start":66
                    }
                ],
                "end":3994,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0028_78_",
                "start":1156,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":93.4,
                        "code":"PF03399",
                        "end":487,
                        "start":253
                    }
                ],
                "end":6666,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0028_79_",
                "start":4292,
                "strand":-1
            },
            {
                "domains":[],
                "end":9377,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0028_80_",
                "start":7409,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":183.1,
                        "code":"PF01728",
                        "end":201,
                        "start":25
                    },
                    {
                        "bitscore":134.8,
                        "code":"PF11861",
                        "end":422,
                        "start":261
                    },
                    {
                        "bitscore":259.9,
                        "code":"PF07780",
                        "end":923,
                        "start":679
                    }
                ],
                "end":14675,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0028_81_",
                "start":11566,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":145.9,
                        "code":"PF00494",
                        "end":649,
                        "start":339
                    }
                ],
                "end":17483,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0028_82_",
                "start":15000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":69.4,
                        "code":"PF08389",
                        "end":257,
                        "start":112
                    },
                    {
                        "bitscore":26.5,
                        "code":"PF03810",
                        "end":102,
                        "start":35
                    }
                ],
                "end":21306,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0028_83_",
                "start":17891,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":149.7,
                        "code":"PF06738",
                        "end":848,
                        "start":607
                    }
                ],
                "end":28637,
                "id":"ncbi_NaganishiafriedmanniiGCA030039255.1_0028_84_",
                "start":24520,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
