var bs_data=[
    {
        "desc":"Naganishia_albida strain Annotation submitted by Air Force Research Laboratory",
        "end":61925,
        "id":"scaffold_14.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":215.3,
                        "code":"PF14533",
                        "end":1351,
                        "start":1147
                    },
                    {
                        "bitscore":273.7,
                        "code":"PF12436",
                        "end":1134,
                        "start":881
                    },
                    {
                        "bitscore":183.7,
                        "code":"PF00443",
                        "end":774,
                        "start":456
                    },
                    {
                        "bitscore":28.5,
                        "code":"PF00917",
                        "end":432,
                        "start":304
                    },
                    {
                        "bitscore":138.7,
                        "code":"PF07047",
                        "end":123,
                        "start":4
                    }
                ],
                "end":8044,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003521-_T1",
                "start":2573,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.7,
                        "code":"PF02752",
                        "end":641,
                        "start":486
                    }
                ],
                "end":12994,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003522-_T1",
                "start":8412,
                "strand":1
            },
            {
                "domains":[],
                "end":14282,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003523-_T1",
                "start":13318,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":333.8,
                        "code":"PF01259",
                        "end":296,
                        "start":16
                    }
                ],
                "end":15722,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003524-_T1",
                "start":14576,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":288.6,
                        "code":"PF00425",
                        "end":478,
                        "start":223
                    },
                    {
                        "bitscore":98.8,
                        "code":"PF04715",
                        "end":165,
                        "start":34
                    }
                ],
                "end":17695,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003525-_T1",
                "start":15782,
                "strand":-1
            },
            {
                "domains":[],
                "end":20580,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003526-_T1",
                "start":17963,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":117.0,
                        "code":"PF06728",
                        "end":369,
                        "start":261
                    },
                    {
                        "bitscore":167.7,
                        "code":"PF06728",
                        "end":264,
                        "start":1
                    }
                ],
                "end":22648,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003527-_T1",
                "start":20713,
                "strand":-1
            },
            {
                "domains":[],
                "end":24731,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003528-_T1",
                "start":23224,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":99.0,
                        "code":"PF07690",
                        "end":543,
                        "start":106
                    }
                ],
                "end":29108,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003529-_T1",
                "start":26835,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.4,
                        "code":"PF02797",
                        "end":298,
                        "start":139
                    }
                ],
                "end":31925,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003530-_T1",
                "start":30000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":97.2,
                        "code":"PF00071",
                        "end":140,
                        "start":37
                    }
                ],
                "end":33588,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003531-_T1",
                "start":32382,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":26.8,
                        "code":"PF09340",
                        "end":62,
                        "start":22
                    }
                ],
                "end":34776,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003532-_T1",
                "start":34009,
                "strand":1
            },
            {
                "domains":[],
                "end":36320,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003533-_T1",
                "start":35307,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":298.3,
                        "code":"PF02781",
                        "end":482,
                        "start":196
                    },
                    {
                        "bitscore":174.3,
                        "code":"PF00479",
                        "end":193,
                        "start":16
                    }
                ],
                "end":38571,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003534-_T1",
                "start":36497,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":73.4,
                        "code":"PF05365",
                        "end":51,
                        "start":3
                    }
                ],
                "end":40381,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003535-_T1",
                "start":39437,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":221.2,
                        "code":"PF01591",
                        "end":393,
                        "start":165
                    },
                    {
                        "bitscore":127.2,
                        "code":"PF00300",
                        "end":581,
                        "start":396
                    },
                    {
                        "bitscore":53.8,
                        "code":"PF04421",
                        "end":876,
                        "start":769
                    }
                ],
                "end":44014,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003536-_T1",
                "start":40901,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.3,
                        "code":"PF00076",
                        "end":107,
                        "start":34
                    }
                ],
                "end":45605,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003537-_T1",
                "start":44558,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":617.1,
                        "code":"PF01603",
                        "end":624,
                        "start":215
                    }
                ],
                "end":49375,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003538-_T1",
                "start":46492,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":103.0,
                        "code":"PF03370",
                        "end":499,
                        "start":390
                    }
                ],
                "end":55404,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003539-_T1",
                "start":52476,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":32.0,
                        "code":"PF08449",
                        "end":410,
                        "start":134
                    }
                ],
                "end":57509,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003540-_T1",
                "start":55653,
                "strand":-1
            },
            {
                "domains":[],
                "end":58409,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003541-_T1",
                "start":57811,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":200.0,
                        "code":"PF13561",
                        "end":260,
                        "start":17
                    }
                ],
                "end":59920,
                "id":"ncbi_NaganishiaalbidaGCA024322255.1_003542-_T1",
                "start":58824,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Naganishia_adeliensis strain 19403212",
        "end":61960,
        "id":"scaffold_22.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2525,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_2-_",
                "start":1866,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":28.7,
                        "code":"PF08449",
                        "end":405,
                        "start":125
                    }
                ],
                "end":4770,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_3-_",
                "start":2863,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":102.5,
                        "code":"PF03370",
                        "end":541,
                        "start":432
                    }
                ],
                "end":8069,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_4-_",
                "start":4990,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":614.2,
                        "code":"PF01603",
                        "end":609,
                        "start":200
                    }
                ],
                "end":15490,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_5-_",
                "start":12605,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.7,
                        "code":"PF00076",
                        "end":107,
                        "start":34
                    }
                ],
                "end":17393,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_6-_",
                "start":16353,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.4,
                        "code":"PF04421",
                        "end":882,
                        "start":775
                    },
                    {
                        "bitscore":108.4,
                        "code":"PF00300",
                        "end":592,
                        "start":398
                    },
                    {
                        "bitscore":219.4,
                        "code":"PF01591",
                        "end":395,
                        "start":168
                    }
                ],
                "end":21059,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_7-_",
                "start":17977,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":178.0,
                        "code":"PF00479",
                        "end":194,
                        "start":16
                    },
                    {
                        "bitscore":294.4,
                        "code":"PF02781",
                        "end":484,
                        "start":196
                    }
                ],
                "end":25571,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_8-_",
                "start":23436,
                "strand":1
            },
            {
                "domains":[],
                "end":26677,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00466_9-_",
                "start":25651,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":81.2,
                        "code":"PF09340",
                        "end":89,
                        "start":14
                    }
                ],
                "end":27911,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_0-_",
                "start":27129,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":147.7,
                        "code":"PF00071",
                        "end":156,
                        "start":10
                    }
                ],
                "end":29669,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_1-_",
                "start":28386,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":43.5,
                        "code":"PF02797",
                        "end":425,
                        "start":266
                    },
                    {
                        "bitscore":81.1,
                        "code":"PF00195",
                        "end":252,
                        "start":19
                    }
                ],
                "end":31960,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_2-_",
                "start":30000,
                "strand":-1
            },
            {
                "domains":[],
                "end":36601,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_3-_",
                "start":33871,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":67.6,
                        "code":"PF01738",
                        "end":274,
                        "start":23
                    }
                ],
                "end":38337,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_4-_",
                "start":36898,
                "strand":1
            },
            {
                "domains":[],
                "end":39005,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_5-_",
                "start":38424,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":24.8,
                        "code":"PF03031",
                        "end":506,
                        "start":375
                    }
                ],
                "end":41422,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_6-_",
                "start":39359,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":73.7,
                        "code":"PF04112",
                        "end":152,
                        "start":20
                    }
                ],
                "end":44520,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_7-_",
                "start":41872,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":153.6,
                        "code":"PF07859",
                        "end":613,
                        "start":402
                    }
                ],
                "end":47686,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_8-_",
                "start":44669,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":69.9,
                        "code":"PF04140",
                        "end":290,
                        "start":195
                    }
                ],
                "end":50488,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00467_9-_",
                "start":49206,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":313.6,
                        "code":"PF00793",
                        "end":355,
                        "start":39
                    }
                ],
                "end":52349,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00468_0-_",
                "start":51058,
                "strand":-1
            },
            {
                "domains":[],
                "end":54799,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00468_1-_",
                "start":52702,
                "strand":-1
            },
            {
                "domains":[],
                "end":58875,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00468_2-_",
                "start":55715,
                "strand":-1
            },
            {
                "domains":[],
                "end":60863,
                "id":"ncbi_NaganishiaadeliensisGCA012922715.1_00468_3-_",
                "start":59375,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
